name: "Markdown action: create indexes"
description: "Creates indexes pages for a markdown styled wiki"
branding:
  icon: activity
  color: green
inputs:
  token:
    description: A github token to use
    required: false
    default: "${{ github.token }}"
outputs:
  amount:
    description: The amount of commits

runs:
  using: "node12"
  main: "dist/index.js"
