name: "Ccommit Amount since Last Release"
description: "This action returns the amount of commits made since the last release"
branding:
  icon: activity
  color: green
inputs:
  token:
    description: A github token to use
    required: false
    default: "${{ github.token }}"
outputs:
  amount:
    description: The amount of commits

runs:
  using: "node20"
  main: "dist/index.js"
